// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jntscvhlsvdgftscxrjd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpudHNjdmhsc3ZkZ2Z0c2N4cmpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNTAyMTQsImV4cCI6MjA3MTgyNjIxNH0.KywaGR6B_-CXWe9vyM64wc3b2BRr7TvCS4_pd3WvIv4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});